version: '3.0'

services:
 buboard-php:
  build: ./Application
  ports:
   - 80:80
  
 buboard-database:
  build: ./Database
  ports:
   - 3306:3306
  volumes:
   - buboard-db:/var/lib/mysql


volumes:
 buboard-db:
