version: '3.0'

services:
 buboard-php:
  build: ./Application
  volumes:
   - ./Application/src:/var/www/html
  ports:
   - 80:80
  
 buboard-database:
  build: ./Database
  ports:
   - 3306:3306
  volumes:
   - buboard-db:/var/lib/mysql



volumes:
 buboard-db:
