version: '3.0'

services:
 buboard-php:
  build: ./Application
  volumes:
   - ./Application/src:/var/www/html
  ports:
   - 80:80
  environment:
    - "HOSTNAME=localhost"
    - "smtpUser=buboard01@gmail.com"
    - "smtpPassword=buboardpassword"
    - "smtpHost=smtp.gmail.com"
    - "smtpPort=587"
  
 buboard-database:
  build: ./Database
  ports:
   - 3306:3306
  volumes:
   - buboard-db:/var/lib/mysql

 phpmyadmin:
  image: phpmyadmin/phpmyadmin
  container_name: phpmyadmin
  environment:
   - PMA_HOST=buboard-database
  ports:
   - 8080:80



volumes:
 buboard-db:
